mirror-to-github:
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - echo "$GITHUB_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - cp "$GITHUB_DEPLOY_KEY" ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
  script:
    - git remote add github git@github.com:spivanatalie64/qt-calculator.git
    - git push github --all --force
    - git push github --tags --force
  only:
    - master
